//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanCapter
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.IO;

    public partial class Paiement
    {
        public int Id { get; set; }
        public Nullable<bool> etat { get; set; }
        public Nullable<System.DateTime> date_E { get; set; }
        public Nullable<System.DateTime> date_P { get; set; }
        public Nullable<int> id_T { get; set; }
        public Nullable<int> id_E { get; set; }
    
        public virtual Etudiant Etudiant { get; set; }
        public virtual Tarif Tarif { get; set; }

        public static readonly string cntStr = @"Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=" + Directory.GetCurrentDirectory() + @"\CanCapterDataBase.mdf;Integrated Security=True";

        public static DataTable getPaiement(int ed)
        {
            SqlDataAdapter adapter = new SqlDataAdapter();
            DataTable dt = new DataTable();
            try
            {
                string rq = String.Format("select P.Id, P.date_E, M.nom as Matiere, P.date_P as 'Date de paiement', T.Prix, P.etat as payé from Paiement P, Tarif T, Matiere M where P.id_T = T.Id_T and P.id_E = {0} and M.Id_M = T.id_M ", ed);
                adapter = new SqlDataAdapter(rq, cntStr)
                {
                    MissingSchemaAction = MissingSchemaAction.AddWithKey
                };
                adapter.Fill(dt);
                SqlCommandBuilder cmd = new SqlCommandBuilder(adapter);
                return dt;
            }
            catch
            {
                return null;
            }
        }


    }
}
