//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanCapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paiement
    {
        public int Id { get; set; }
        public Nullable<bool> etat { get; set; }
        public Nullable<System.DateTime> date_E { get; set; }
        public Nullable<System.DateTime> date_P { get; set; }
        public Nullable<int> id_T { get; set; }
        public Nullable<int> id_E { get; set; }
    
        public virtual Etudiant Etudiant { get; set; }
        public virtual Tarif Tarif { get; set; }
    }
}
