//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanCapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recu()
        {
            this.Rrecu_Paiment = new HashSet<Rrecu_Paiment>();
        }
    
        public int Id_R { get; set; }
        public int Id_E { get; set; }
        public System.DateTime date_P { get; set; }
        public double Paye { get; set; }
        public double Rest { get; set; }
        public double Total { get; set; }
        public bool Statut { get; set; }
        public Nullable<System.DateTime> date_E { get; set; }
        public string observation { get; set; }
    
        public virtual Etudiant Etudiant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rrecu_Paiment> Rrecu_Paiment { get; set; }
    }
}
