//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanCapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rrecu_Paiment
    {
        public int Id { get; set; }
        public string Url_Recu { get; set; }
        public System.DateTime date_E { get; set; }
        public int Id_R { get; set; }
        public Nullable<double> Paye { get; set; }
    
        public virtual Recu Recu { get; set; }
    }
}
